---
format: html
---

# Soil Microbial Data Qiime2 Pipeline Commands

Two folders labeled as soil_microbial_original and soil-microbial-work

**soil_microbial_original** original sequences

**soil-microbial-work/qiime_workflow** active working directory with data with associate working directories

-- metadata

-- results

- results/visualizations

- results/artifacts


Created a directory to place all associated data
```bash
mkdir qiime_workflow
```

Activated conda environment
```bash
conda activate qiime2_v2024.10.1
```

uploaded updated metadata file (see metadata_clean.py)
```bash
qiime metadata tabulate \
  --m-input-file metadata/Nachusa_16s_all_metadata_edited2.tsv \
  --o-visualization metadata-output/soil-metadata-viz.qzv
```
import single end forward sequences
```bash
qiime tools import \
--type MultiplexedSingleEndBarcodeInSequence \
--input-path /mnt/HDD/samanthag/soil-microbial-original/01id01NB_S1_R1_001.fastq.gz \
--output-path ./results/artifacts/multiplexed-seqs.qza
```

Demultiplexed the single-end sequences in the background. Output should include demultiplexed-seqs.qza that is the updated version. 
```bash

 qiime cutadapt demux-single \
  --p-cores 16 \
  --p-minimum-length 150 \
  --i-seqs ./results/artifacts/multiplexed-seqs.qza \
  --m-barcodes-file ./metadata/Nachusa_16s_all_metadata_edited2.tsv \
  --m-barcodes-column barcode-sequence \
  --p-error-rate 0   \
  --o-per-sample-sequences ./results/artifacts/demultiplexed-seqs2.qza \
  --o-untrimmed-sequences ./results/artifacts/untrimmed-seqs2.qza \
  --verbose 
```

Created a visualization demux quality plot, will trim at 275
```bash

qiime demux summarize \
  --i-data ./results/artifacts/demultiplexed-seqs2.qza \
  --o-visualization ./results/visualizations/demultiplexed-seqs2.qzv
```
create a deblur working directory 
```bash
mkdir HOME/soil-microbial-work/qiime_workflow/deblur
```


```bash
qiime quality-filter q-score \
 --i-demux ./results/artifacts/demultiplexed-seqs2.qza \
 --o-filtered-sequences ./deblur/demux-filtered-deblur2.qza \
 --o-filter-stats ./deblur/demux-filter-stats-deblur2.qza 
 ```

Run deblur(need to run deblur)
```bash
qiime deblur denoise-16S \
  --i-demultiplexed-seqs ./deblur/demux-filtered-deblur2.qza \
  --p-trim-length 275 \
  --p-jobs-to-start 16 \
  --o-representative-sequences ./deblur/rep-seqs-deblur2.qza \
  --o-table ./deblur/table-deblur2.qza \
  --p-sample-stats \
  --o-stats ./deblur/deblur-stats2.qza \
  --verbose 
```

Create visualizations 
```bash
qiime metadata tabulate \
  --m-input-file ./deblur/demux-filter-stats-deblur2.qza \
  --o-visualization ./results/visualizations/demux-filter-stats-deblur2.qzv
```

```bash
qiime deblur visualize-stats \
  --i-deblur-stats ./deblur/deblur-stats2.qza \
  --o-visualization ./results/visualizations/deblur-stats2.qzv
```

Create a feature table summary 
```bash
qiime feature-table summarize \
  --i-table ./deblur/table-deblur2.qza \
  --o-visualization ./results/visualizations/table-deblur2.qzv \
  --m-sample-metadata-file ./metadata/Nachusa_16s_all_metadata_edited2.tsv
  ```

provides a mapping of feature IDs to sequences, and links to easily BLAST each sequence against the NCBI nt database

  ```bash
qiime feature-table tabulate-seqs \
  --i-data ./deblur/rep-seqs-deblur2.qza \
  --o-visualization ./results/visualizations/rep-seqs2.qzv
  ```
